homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.518
  longitude: -74.8453
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_user 
    password: !secret unifi_password
    new_device_defaults:
	track_new_devices: false
	hide_if_away: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
